### ISSUE TITLE
map_contracts: wasm execution failed deterministically: panic

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-erc20-contracts#1]
panic issue:

**Block number: 813375** (ETH)

> eth-substreams run --start-block 813370 https://github.com/pinax-network/substreams-erc20-contracts/releases/download/v0.1.2/erc20-contracts-v0.1.2.spkg graph_out --production-mode

```
----------- BLOCK #840,760 (77e4695c56bf20719ae302528b5c397e52f5de53bdca8a428f9ce210c0703d80) ---------------
----------- BLOCK #840,761 (a7c846eb95de5d69801c946c329ce6939db28b63cac336ad4c9adbde799fc3eb) ---------------
Error: rpc error: code = Unknown desc = rpc error: code = InvalidArgument desc = step new irr: handler step new: execute modules: applying executor results "map_contracts": execute: maps wasm call: block 10635344: module "map_contracts": wasm execution failed deterministically: panic in the wasm: "called `Option::unwrap()` on a `None` value" at /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/substreams-0.5.10/src/scalar.rs:565:25
----- stack trace -----
log: get_contract_name: "8e10c1a0d80018354944093be9a7e2cbdd6c437f"
log: get_contract_symbol: "8e10c1a0d80018354944093be9a7e2cbdd6c437f"
log: get_contract_decimals: "8e10c1a0d80018354944093be9a7e2cbdd6c437f"
```

## ❌ Error
```bash
const error = new ConnectError(status.message, status.code, headerOrTrailer);

^

ConnectError: [unknown] rpc error: code = InvalidArgument desc = step new irr: handler step new: execute modules: applying executor results "map_contracts": execute: maps wasm call: block 10635344: module "map_contracts": wasm execution failed deterministically: panic in the wasm: "called `Option::unwrap()` on a `None` value" at /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/substreams-0.5.10/src/scalar.rs:565:25

----- stack trace -----

log: get_contract_name: "8e10c1a0d80018354944093be9a7e2cbdd6c437f"

log: get_contract_symbol: "8e10c1a0d80018354944093be9a7e2cbdd6c437f"

log: get_contract_decimals: "8e10c1a0d80018354944093be9a7e2cbdd6c437f"

at findTrailerError (file:///node_modules/@bufbuild/connect-node/node_modules/@bufbuild/connect/dist/esm/protocol-grpc/trailer-status.js:80:23)

at validateTrailer (file:///node_modules/@bufbuild/connect-node/node_modules/@bufbuild/connect/dist/esm/protocol-grpc/validate-trailer.js:22:17)

at file:///node_modules/@bufbuild/connect-node/node_modules/@bufbuild/connect/dist/esm/protocol-grpc/transport.js:144:37

at Generator.next (<anonymous>)

at resume (file:///node_modules/@bufbuild/connect-node/node_modules/@bufbuild/connect/dist/esm/protocol-grpc/transport.js:32:44)

at fulfill (file:///node_modules/@bufbuild/connect-node/node_modules/@bufbuild/connect/dist/esm/protocol-grpc/transport.js:34:31)

at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {

rawMessage: 'rpc error: code = InvalidArgument desc = step new irr: handler step new: execute modules: applying executor results "map_contracts": execute: maps wasm call: block 10635344: module "map_contracts": wasm execution failed deterministically: panic in the wasm: "called `Option::unwrap()` on a `None` value" at /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/substreams-0.5.10/src/scalar.rs:565:25\n' +
```

## Last pushed block

```yaml
},

clock: {

timestamp: '2016-01-07T21:33:32.000Z',

number: 813375,

id: '5bce4c6bea5a6e046dec3cb7a36054d1b348834e47c8b8ca2288041c83652775'

},

manifest: {

substreamsEndpoint: 'https://eth.substreams.pinax.network:9000'/;,

chain: 'eth',

finalBlockOnly: 'false',

moduleName: 'graph_out',

type: 'sf.substreams.sink.entity.v1.EntityChanges',

moduleHash: 'dd6cc2c1bbe1516bb4bddcd9a8ca47e1861f5609'

}
```
